Algoritmo "EXERCICIO22"
Var
// Seção de Declarações das variáveis 
   valor_compra, acrescimo, valor_final:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   
   Escreva("Digite o valor da compra:")
   Leia(valor_compra)

   Escreva("Digite o valor acrescimo:")
   Leia(acrescimo)

   
   valor_final<- valor_compra+0.12
   
Escreva("O valor final da compra sera:",valor_final)

Fimalgoritmo