Algoritmo "Exercicio19"
Var
// Seção de Declarações das variáveis 
  base_menor, base_maior, altura, area: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreva("Digite o valor da base maior:")
  Leia(base_maior)
  Escreva("Digite o valor da base menor:")
  Leia(base_menor)
  Escreva("Digite o valor da altura:")
  Leia(altura)
  
  area<-((base_maior + base_menor) * altura)/2
  
  Escreva("A area do trapezio equivale a:",area)
Fimalgoritmo