Algoritmo "Exercicio6"
Var
// Seção de Declarações das variáveis 
   BASE, ALTURA, AREA: REAL
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA("Digite o valor da base do triângulo:")
   LEIA(BASE)
   
   ESCREVA("Digite o valor da altura do triângulo")
   LEIA(ALTURA)
   
   AREA <- BASE * ALTURA

   ESCREVA("A VALOR DA ÁREA É :", AREA)

Fimalgoritmo