Algoritmo "Exercicio13"
Var
// Seção de Declarações das variáveis 
   MASSA, ACELERACAO, RESULTADO: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA("Digite o valor da MASSA: Kg ")
   LEIA(MASSA)
   
   ESCREVA("Digite o valor de ACELERACAO: m/s ")
   LEIA(ACELERACAO)
   
   RESULTADO <- MASSA * ACELERACAO
   
   ESCREVA("O FORÇA RESULTANTE SERÁ DE APROXIMADAMENTE:", RESULTADO)

Fimalgoritmo