Algoritmo "Exercicio17"
Var
// Seção de Declarações das variáveis 
   raio, volume, pi_valor:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite o valor do raio:")
   Leia(raio)
   
   Escreva("Digite o valor de pi:")
   Leia(pi_valor)
   
   Volume<- (4/3) * pi_valor * raio^3

   Escreval("O volume da esfera equivale a:", volume)
Fimalgoritmo