Algoritmo "Exercicio1"
Var
// Seção de Declarações das variáveis 
    Valor1, Valor2, Soma: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA("Digite o pirmeiro valor:")
   LEIA(Valor1)

   ESCREVA("Digite o segundo valor:")
   LEIA(Valor2)
   
   Soma <- Valor1 + Valor2
   
   ESCREVA("A SOMA DOS NÚMERO RESULTARÁ EM:", Soma)
   
Fimalgoritmo