Algoritmo "Exercicio15"
Var
// Seção de Declarações das variáveis 
   ValorA, ValorB, ValorC, ValorD, ValorE, ValorF, ValorX, ValorY:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite o valor de A:")
   Leia(ValorA)
   
   Escreva("Digite o valor de B:")
   Leia(ValorB)
   
   Escreva("Digite o valor de C:")
   Leia(ValorC)
   
   Escreva("Digite o valor de D:")
   Leia(ValorD)
   
   Escreva("Digite o valor de E:")
   Leia(ValorE)
   
   Escreva("Digite o valor de F:")
   Leia(ValorF)


   
   ValorX <-((ValorC*ValorE)-(ValorB*ValorF)) / ((ValorA*ValorE)-(ValorB*ValorD))

   Escreva("O valor de X e:",ValorX)
   
   ValorY <-((ValorA*ValorF)-(ValorC*ValorD)) /((ValorA*ValorE)-(ValorB*ValorD))

   Escreva(" / O valor de Y e:",ValorY)

Fimalgoritmo