Algoritmo "Exercicio12"
Var
// Seção de Declarações das variáveis 
   VELOCIDADE, TEMP, DISTANCIA: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA("Digite o valor da VELOCIDADE: m/s ")
   LEIA(VELOCIDADE)
   
   ESCREVA("Digite o valor do TEMPO necessário: s ")
   LEIA(TEMP)
   
   DISTANCIA <- VELOCIDADE * TEMP
   
   ESCREVA("A DISTÂNCIA PERCORRIDA SERÁ:", DISTANCIA)

Fimalgoritmo