Algoritmo "EXERCICIO21"
Var
// Seção de Declarações das variáveis 
   distancia_p, tempo_gasto, velocidade_media: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o valor da distancia percorrida:")
   Leia(distancia_p)
   Escreva("Digite o valor da tempo gasto:")
   Leia(tempo_gasto)
   
   velocidade_media<- distancia_p/ tempo_gasto
   Escreva("A velocidade media da viagem foi aproximadamente:",velocidade_media)
Fimalgoritmo