Algoritmo "Exercicio18"
Var
// Seção de Declarações das variáveis 
  corrente_eletrc, resistencia, tensao:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite o valor da corrente eletrica:")
   Leia(corrente_eletrc)

   Escreva("Digite o valor da resistencia:")
   Leia(resistencia)
   
   tensao<-resistencia*corrente_eletrc
     Escreval("O valor da tensao equivale a:",tensao)

Fimalgoritmo